### ISSUE TITLE
Update mentor availability after each added connection

### ISSUE THREAD

**Issue by ageller** [CIERA-Northwestern/JEDI_ext_mentorship#2]
Noted from Tjitske's pull request

**Comment by TStarkenburg** [comment]
Also requires updating how many mentees from different roles a mentor wants after each added connection.

And after every connection round in addition to updating how many mentors a mentee still needs, also update how many mentors from what roles...

**Comment by ageller** [comment]
Does the current code try to match mentors of a given role to mentees based on mentee preferences?  (I don't see it in there.)  Or is that taken care of in the metrics?  (or do we need to add that.)  This may be a good subject for another issue, if I'm understanding correctly.  P 

My most recent pull request addresses the issue with mentors being oversubcribed (by max number and role-by-role), but it doesn't address the mentee preferences.

**Comment by TStarkenburg** [comment]
Yes, I think your pull request addresses this issue, and we've moved to the other one on the mentee updates :) 
Part of the matching_round function may actually be redundant now, but we can de clean-up later.

**Comment by TStarkenburg** [comment]
This one can be closed now too, right?
