### ISSUE TITLE
use "binary" checks while creating network

### ISSUE THREAD

**Issue by ageller** [CIERA-Northwestern/JEDI_ext_mentorship#20]
In Aaron's pull request about combining metrics, he's including the binary checks that we have in the combined metric.  We should remove those checks (from the input metrics dict to create_best_network), and instead include these metrics while creating the network.  That way if we fail the check, we generate a new network, and we always create the requested number of valid networks.

**Comment by ageller** [comment]
Most importantly, we need to throw out a network if any avoid is matched

**Comment by agurvich** [comment]
second most important is to throw out a network if any mentee does not receive a mentor

**Comment by agurvich** [comment]
Closed by 8e913569
