### ISSUE TITLE
Update preferences part in survey

### ISSUE THREAD

**Issue by ageller** [CIERA-Northwestern/JEDI_ext_mentorship#27]
1. The part of the survey where we ask for preferences should be a separate section that everyone goes to.  (Currently it is repeated for each role.)
2. We also want to convert this to multiple (identical) dropdowns or bunch of checkboxes perhaps using [form_ranger](https://workspace.google.com/marketplace/app/form_ranger/387838027286) and build this part from a csv of CIERA people.

Note: (1.) will also change the shape of the input data

**Comment by agurvich** [comment]
this is done but requires some documentation/instructions for anyone but me to use it. i can maybe record myself putting it together using some of our fake names?
