### ISSUE TITLE
Add metric to track if we ran out of mentors (and mentees are left unassigned)

### ISSUE THREAD

**Issue by ageller** [CIERA-Northwestern/JEDI_ext_mentorship#3]
This may happen due to the sorting algorithm, placing mentees who selected fewer mentors at highest priority.  If there aren't enough mentors, mentees who selected a log of mentors may not get matched with any.

**Comment by TStarkenburg** [comment]
We already have a metric that measures whether all mentees have at least one mentor. And also one that measures what fraction of mentees got less mentors than requested.

**Comment by TStarkenburg** [comment]
And in the first round all mentees get assigned one mentor, so you'd only run into this problem when there are less available mentee spots for all mentors combined (sum(mentor.max_mentees)) than number of mentees.
