### ISSUE TITLE
Add a metric that prioritizes difference in rank for mentorship matching

### ISSUE THREAD

**Issue by agurvich** [CIERA-Northwestern/JEDI_ext_mentorship#48]
As it is now, a mentor is considered eligible if their rank is simple greater than the mentee's. That should stay the same. However, it is heuristically "better" if the network has a median difference in rank between mentors and mentees that is larger (e.x. don't want to pair a bunch of grad students who are only 1 year apart w/ one another and then have the most senior grad student paired with the most junior). 

In particular, this would help de-prioritize networks where grad students who are ~1 year apart are assigned to one-another when there might be more effective matches.

**Comment by TStarkenburg** [comment]
Just for clarification: ranks here means ranks within a certain role (as in 1.2 and 1.4 being both grad students but from different years). So the goal is that peer mentors are optimized to be further apart in seniority so we try to avoid having peer mentors who are only 1 year apart if possible.

**Comment by TStarkenburg** [comment]
Added a metric to minimize the fraction of peer mentoring pairs that had difference in years < 2. I also added a requirement in the mentor matching so acceptable peer mentors are only those with Delta(years) > 1. These are still included in possible alternative mentors.

**Comment by agurvich** [comment]
Is there a matching PR you wanted me to look at or not yet? I'm surprised the peer mentoring requirement wasn't already in there. Good catch.

**Comment by TStarkenburg** [comment]
PR is there now, sorry. There was a peer mentoring requirement there but only requiring the mentor being more senior than the mentee. I updated that to require more senior by at least 2 years.
