### ISSUE TITLE
Decide how to combine metrics to pick best network(s)

### ISSUE THREAD

**Issue by ageller** [CIERA-Northwestern/JEDI_ext_mentorship#5]

**Comment by TStarkenburg** [comment]
Some ideas:
- these need to be satisfied in all cases (tests of the method): 
    -> nobody is assigned to someone from their avoid list; 
    -> no mentor is assigned more mentees than they volunteered for
- most important:
    -> every mentee has at least one mentor 
    -> ?
- desired:
    -> large fraction of mentors has extra slots (so gets less assigned than volunteered)
    -> small fraction of mentees gets less than requested mentors
    -> for a large fraction of mentees that had preferences at least one gets satisfied
    -> as many pods or dense groups as possible

**Comment by ageller** [comment]
I added some first attempt at creating a combined metric within the ipynb file.  Its mostly "quick and dirty" to see what comes out.  We will also have to call the code a little differently so that we save the networks as they are created (so that we can select the best one from the iterations, based on the combined metric).  That will be easy enough to do, but wanted to point it out here.

**Comment by ageller** [comment]
We should store the metrics in a dict.   Some metrics can be binary (yes/no), and if no then throw out the realization.  The rest of the metrics should have a weight.   Then we take the weighted average and pick the top for our network.

**Comment by TStarkenburg** [comment]
It may be helpful to think about them as separate "code checks" and "metrics"?

**Comment by ageller** [comment]
I created a pull request that has a function to combine the metrics as we discussed.  Please look over the code and the output to check for bugs.  I don't have time to do an exhaustive check right now.
