### ISSUE TITLE
match mentors to mentee based on mentee's role preference

### ISSUE THREAD

**Issue by ageller** [CIERA-Northwestern/JEDI_ext_mentorship#7]
I don't think this is currently in the code, other than the metric of "frac_mentees_atleast_one_preference".  (I could be missing that.)  Should we build in a way to enforce this in the code?  For instance, in "find_mentor" we could limit the "mentors_avoided" list to only include mentors that are within roles that the mentee still needs.  (I could work on this later, if someone else doesn't get to it first.)

**Comment by TStarkenburg** [comment]
This is in the code (the avoided list in find_mentors does include only mentors from roles the mentee wants mentors for)

**Comment by TStarkenburg** [comment]
It just doesn't get updated yet (should probably be updated like you do the mentors' matches per role in your pull request)

**Comment by ageller** [comment]
Got it.  Ok maybe we need a similar function to my pull request of "check_mentor_availability", e.g., a "check_mentee_needed" function using my "has_n_role_mentors" list.  I'll see if I have time later today to work on that.  Otherwise, Monday.  (Or someone else can beat me to it.)

**Comment by ageller** [comment]
I added that function, and it should be included in my pull request.

**Comment by TStarkenburg** [comment]
Question: we're now only matching for requested roles. So we're basically saying that if a mentee/mentor signed up for mentors/mentees from particular roles they will never get a mentor/mentee from another role. Is this too strict?
Another option is to see the role input as preferences and match mentee/mentors to mentors/mentees from other roles (still always peer or more senior/junior) if their preferred roles cannot be matched?
We can also see how well this works for now, but for a full rollout in may be good to include options here (for example as initial settings)?

**Comment by ageller** [comment]
You raise a good point.  I was thinking of these preferences as being strict, e.g., if as a mentee I only want 1 postdoc mentor, I should only get one (not two).  We should return to this if we find that we get mentees who are not matched to mentors.  If that happens AND there are mentors left, then we can relax criteria to see if we can match. 

Another related through (we can open a different issue if necessary): what happens if the mentee filling out the survey does not specify any number of mentors from the different categories?  Is that set to zero? (in which case they would not get any mentors -- which is probably fine.)  But more importantly, should we include an option in the survey to just pick N total mentors (without specifying the role)?  And/or should we allow an option for any number of mentors of a given role (without specifying a precise number)?

**Comment by TStarkenburg** [comment]
I think this is still related to this issue so discussing here is fine to me. To answer your questions:
- In the survey a mentee can only specify how many mentors from which role, so if there is no specification there this mentee is not requesting _any_ mentors.
- I like the suggestion of including an option "give me _n_ mentors, from whatever role", and then we can make sure these will be peer/more senior? Even more we could ask for the number requested from specific roles and if a mentee wants additional mentors but doesn't care from which role they can add that too?
- The last suggestion is partly covered by the previous option. Also we only allow for 0, 1, or 2 mentors from each role, so I'm not sure how much "any" would add to that.

**Comment by agurvich** [comment]
I also envisioned the role preferences as being strict, so if someone put 0 for all the roles I'd consider them not requesting any mentors (which would be weird). 

I like the idea of having an an "N any of the above" as the last option on the list so an undergrad can ask for up to 2 additional mentors from the above category for a maximum total of 10(!) mentors. 2 undergrad peer | 2 grad | 2 post doc | 2 faculty | 2 flexible

**Comment by ageller** [comment]
OK.  Let's leave this open for now.  We should discuss this at our next group meeting, and then think about how to implement it (since there will be survey and code changes).

**Comment by TStarkenburg** [comment]
I implemented an option to suggest alternative mentors if no mentor of preferred roles is available (the alternative always having a more senior role than the mentee). Based on doing that I think asking whether mentees would be interested in alternatives if otherwise no mentor of the requested role is available might be better than asking "any of the above" in addition to the role requests. We could add "any of the above" as well but I think that should be in place of asking mentors of specific roles. What do you think?
